_wandb:
    value:
        cli_version: 0.19.3
        code_path: code/main_run.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 1
                - 13
                - 14
                - 16
                - 23
                - 35
                - 55
                - 61
                - 62
            "4": 3.10.16
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
choose_best_model_on:
    value: dev_loss
do_dev_every_n_epochs:
    value: 1
env_name:
    value: inventory
epochs:
    value: 1000
epochs_between_save:
    value: 1
exp_name:
    value: hybrid_general
load_model_path:
    value: models/saved_models/your_model.pt
load_previous_model:
    value: false
logging_params:
    value:
        env_name: inventory
        exp_name: hybrid_general
        use_tensorboard: true
        use_wandb: true
        wandb_entity: alvomatias
        wandb_project_name: inventory_control
observation_params:
    value:
        demand:
            past_periods: 0
            period_shift: 0
        include_past_observations:
            arrivals: 0
            orders: 0
        include_static_features:
            holding_costs: true
            lead_times: true
            mean: false
            procurement_costs: true
            std: false
            underage_costs: true
            upper_bounds: false
        include_warehouse_inventory: false
        sample_features: null
        sample_features_file: null
        time_features: null
        time_features_file: null
params_by_dataset:
    value:
        dev:
            batch_size: 1024
            ignore_periods: 16
            n_samples: 8192
            periods: 50
        test:
            batch_size: 1024
            ignore_periods: 16
            n_samples: 8192
            periods: 30
        train:
            batch_size: 1024
            ignore_periods: 16
            n_samples: 8192
            periods: 50
print_results_every_n_epochs:
    value: 1
problem_params:
    value:
        discrete_features:
            fixed_ordering_cost:
                thresholds:
                    - -0.0001
                    - 0
                    - 1
                    - 2
                    - 3
                    - 4
                    - 5
                    - 6
                    - 7
                    - 8
                    - 9
                values:
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
                    - 0
        is_hybrid: true
        lost_demand: true
        maximize_profit: false
        n_extra_echelons: 0
        n_stores: 1
        n_warehouses: 0
save_model:
    value: false
save_model_filename:
    value: 1737926962
save_model_folders:
    value:
        - "2025_01_26"
        - hybrid_policy
use_tensorboard:
    value: true
use_wandb:
    value: true
wandb_entity:
    value: alvomatias
wandb_project_name:
    value: inventory_control
