name: exp_neural
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python and scientific computing
  - python=3.10.12
  - numpy>=1.21.0
  - pandas>=1.4.0
  - scipy>=1.8.0
  - scikit-learn>=1.1.0
  
  # PyTorch ecosystem
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # or 12.1 depending on your CUDA version
  
  # Visualization and plotting
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Jupyter and development
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  
  # Data handling and utilities
  - pyyaml>=6.0
  - tqdm>=4.60.0
  - pillow>=9.0.0
  
  # RL and simulation
  - gymnasium>=0.28.0
  
  # Package manager
  - pip
  
  # Pip-only packages
  - pip:
    # Core RL libraries
    - torchrl>=0.2.0
    - tensordict>=0.2.0
    
    # Logging and monitoring
    - wandb>=0.15.0
    - tensorboard>=2.10.0
    
    # Distributed computing
    - ray[default]>=2.5.0
    
    # Data processing
    - openpyxl>=3.0.0
    - statsmodels>=0.13.0
    
    # Web and utilities
    - beautifulsoup4>=4.11.0
    - requests>=2.28.0
    
    # Additional useful packages
    - plotly>=5.0.0  # for interactive plots
    - plotly-orca>=1.3.0  # for static plot export
    - jupyter-dash>=0.4.0  # for interactive dashboards
    - memory-profiler>=0.60.0  # for memory profiling
    - psutil>=5.9.0  # for system monitoring