# Fixed Costs Grid Search Sweep Configuration
config_files:
  setting: 'configs/settings/fixed_costs_heterogen.yml'

# method: 'random'
method: 'grid'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  stores:
    values: [50, 1, 30, 3, 20, 5, 10, 7]
  batch_size:
    values: [128, 64]
  a_seed:
    values: [0, 1, 2, 3, 4]
  fixed_cost:
    values: [320]