# Fixed Costs Grid Search Sweep Configuration
config_files:
  setting: 'configs/settings/fixed_costs_heterogen.yml'

# method: 'random'
method: 'grid'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  stores:
    # values: [50, 30, 10, 5]
    # values: [100, 70, 50, 30, 20, 10]
    values: [50, 1, 30, 3, 20, 5, 10, 7]
  batch_size:
    values: [128]
    # values: [64, 128]
    # values: [32]
  a_seed:
    # values: [0]
    # values: [0, 1, 2, 3, 4]
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  fixed_cost:
    values: [64]
    # values: [50, 64, 70, 80, 90, 100, 150]
    # values: [100, 150, 200, 250, 300]