# Fixed Costs Grid Search Sweep Configuration
config_files:
  setting: 'configs/settings/fixed_costs_cos_sim.yml'

parameters:
  normalize_observations:
    values: [False]
  fixed_cost:
    values: [64]
  batch_size:
    values: [128, 256]
  seed:
    values: [0, 1, 2]