# Number of Stores Setting Sweep Configuration
config_files:
  setting: 'configs/settings/fixed_costs.yml'

parameters:
  normalize_observations:
    values: [False]
  n_stores:
    values: [1, 10]
    # values: [1, 2, 3, 5, 7, 10]
    distribution: 'categorical'  # This ensures values are selected uniformly
  seed:
    values: [0, 1, 2, 3, 4, 5]
    distribution: 'categorical'  # This ensures values are selected uniformly
