wandb_version: 1

epochs:
  desc: null
  value: 1000
do_dev_every_n_epochs:
  desc: null
  value: 1
print_results_every_n_epochs:
  desc: null
  value: 1
save_model:
  desc: null
  value: false
epochs_between_save:
  desc: null
  value: 1
choose_best_model_on:
  desc: null
  value: dev_loss
load_previous_model:
  desc: null
  value: false
load_model_path:
  desc: null
  value: models/saved_models/your_model.pt
save_model_folders:
  desc: null
  value:
  - '2025_01_16'
  - hybrid_policy
save_model_filename:
  desc: null
  value: 1737041706
logging_params:
  desc: null
  value:
    use_wandb: true
    wandb_project_name: inventory_control
    wandb_entity: alvomatias
    exp_name: hybrid_general
    env_name: inventory
problem_params:
  desc: null
  value:
    n_stores: 1
    n_warehouses: 0
    n_extra_echelons: 0
    lost_demand: true
    maximize_profit: false
    is_hybrid: true
    discrete_features:
      fixed_ordering_cost:
        thresholds:
        - -0.0001
        - 0.0
        - 1.0
        - 2.0
        - 3.0
        - 4.0
        - 5.0
        - 6.0
        - 7.0
        - 8.0
        - 9.0
        values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
observation_params:
  desc: null
  value:
    include_warehouse_inventory: false
    include_static_features:
      holding_costs: true
      underage_costs: true
      procurement_costs: true
      lead_times: true
      upper_bounds: false
      mean: false
      std: false
    demand:
      past_periods: 0
      period_shift: 0
    include_past_observations:
      arrivals: 0
      orders: 0
    time_features_file: null
    time_features: null
    sample_features_file: null
    sample_features: null
params_by_dataset:
  desc: null
  value:
    train:
      n_samples: 8192
      batch_size: 1024
      periods: 50
      ignore_periods: 16
    dev:
      n_samples: 8192
      batch_size: 1024
      periods: 50
      ignore_periods: 16
    test:
      n_samples: 8192
      batch_size: 1024
      periods: 30
      ignore_periods: 16
use_wandb:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: inventory_control
wandb_entity:
  desc: null
  value: alvomatias
exp_name:
  desc: null
  value: hybrid_general
env_name:
  desc: null
  value: inventory
_wandb:
  desc: null
  value:
    code_path: code/main_run.py
    python_version: 3.10.16
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737041707.0
    t:
      1:
      - 1
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
