# Fixed Continuous Baseline Sweep Configuration
config_files:
  hyperparams: 'configs/policies/fixed_continuous_hybrid.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  anneal_lr:
    values:
      - false
  buffer_periods:
    values:
      - 20
  clip_coef:
    values:
      - 0.16
  fixed_cost:
    distribution: categorical
    values:
      - 64
  gae_lambda:
    values:
      - 0.96
  gamma:
    values:
      - 0.93
  learning_rate:
    values:
      - 0.001
  max_grad_norm:
    values:
      - 5.0
  normalize_advantages:
    values:
      - true
      - false
  normalize_by_mean_demand:
    values:
      - true
  disable_cross_term:
    values:
      - false
      - true
  normalize_observations:
    values:
      - false
  num_epochs:
    values:
      - 5
  policy_activation:
    values:
      - Tanh
  reward_scaling:
    values:
      - true
  use_gae:
    values:
      - true
  value_activation:
    values:
      - Tanh
  value_function_coef:
    values:
      - 0.13
  use_wandb:
    values:
      - true
