# Gaussian PPO Separate Net Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/gaussian_ppo_separate_net.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  anneal_lr:
    values:
      - false
  anneal_entropy_coef:
    values:
      - true
  min_entropy_coef:
    values:
      - 0.001
  entropy_coef:
    distribution: log_uniform_values
    max: 0.1
    min: 0.005
  buffer_periods:
    values:
      - 20
  clip_coef:
    values:
      - 0.15
  gae_lambda:
    values:
      - 0.96
  gamma:
    values:
      - 0.93
  learning_rate:
    values:
      - 0.001
  max_grad_norm:
    values:
      - 5.0
  normalize_advantages:
    values:
      - true
  normalize_by_mean_demand:
    values:
      - true
  normalize_observations:
    values:
      - false
  num_epochs:
    values:
      - 5
      - 3
  policy_activation:
    values:
      - Tanh
      - ELU
  reward_scaling:
    values:
      - true
  use_gae:
    values:
      - true
  value_activation:
    values:
      - Tanh
  value_function_coef:
    values:
      - 0.15
  use_wandb:
    values:
      - true
  continuous_shift:
    values:
      - 1.0
      - 5.0