# Gumbel Softmax Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/gumbel_softmax.yml'
  setting: 'configs/settings/fixed_costs_finite_thresh.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  add_gumbel_noise:
    values:
      - true
      - false
  anneal_lr:
    values:
      - true
  buffer_periods:
    values:
      - 50
  initial_temperature:
    distribution: uniform
    max: 1
    min: 0.9
  learning_rate:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  max_grad_norm:
    distribution: uniform
    max: 10
    min: 5
  min_temperature:
    distribution: log_uniform_values
    max: 0.2
    min: 0.001
  policy_activation:
    values:
      - Tanh
      # - ELU
      # - ReLU
  reward_scaling:
    values:
      - true
  reward_scaling_pathwise:
    values:
      - true
  temperature_decay:
    values:
      - 1
  use_straight_through:
    values:
      - true
  use_wandb:
    values:
      - true
  pathwise_coef:
    distribution: uniform
    max: 10
    min: 8