# Gumbel Softmax Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/gumbel_softmax.yml'

# method: 'grid'
method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  add_gumbel_noise:
    values:
      - true
  anneal_lr:
    values:
      - true
  buffer_periods:
    values:
      - 20
  clip_by_component:
    values:
      - true
  learning_rate:
    values:
      - 0.005
  max_grad_norm:
    values:
      - 5
  entropy_coef:
    values:
      - 0.0005
  policy_activation:
    values:
      - ELU
  reward_scaling_pathwise:
    values:
      - true
  use_straight_through:
    values:
      - true
  use_wandb:
    values:
      - true
  continuous_scale:
    values:
      - 1.0
  continuous_shift:
    values: 
      - 1.0