# Gumbel Softmax Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/gumbel_softmax.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  add_gumbel_noise:
    values:
      - true
  anneal_lr:
    values:
      - true
  buffer_periods:
    values:
      - 10
      - 30
  clip_by_component:
    values:
      - true
  learning_rate:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  max_grad_norm:
    distribution: uniform
    max: 10
    min: 1
  entropy_coef:
    distribution: log_uniform_values
    max: 0.1
    min: 0.0001
  normalize_observations:
    values:
      - false
  policy_activation:
    values:
      - Tanh
      - ELU
  reward_scaling_pathwise:
    values:
      - true
  use_straight_through:
    values:
      - true
  use_wandb:
    values:
      - true