# Gumbel Softmax Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/gumbel_softmax.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  add_gumbel_noise:
    values:
      - true
      - false
  initial_temperature:
    distribution: log_uniform_values
    max: 1
    min: 0.5
  min_temperature:
    distribution: log_uniform_values
    max: 0.2
    min: 0.001
  temperature_decay:
    distribution: log_uniform_values
    max: 0.99
    min: 0.95
  anneal_lr:
    values:
      - true
  buffer_periods:
    values:
      - 10
      - 20
  clip_by_component:
    values:
      - true
  learning_rate:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  max_grad_norm:
    distribution: log_uniform_values
    max: 10
    min: 0.1
  entropy_coef:
    distribution: log_uniform_values
    max: 0.1
    min: 0.0001
  normalize_observations:
    values:
      - false
  policy_activation:
    values:
      - ELU
  reward_scaling_pathwise:
    values:
      - true
  use_straight_through:
    values:
      - true
  normalize_by_mean_demand:
    values:
      - true
      - false
  use_wandb:
    values:
      - true