# Hybrid Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/hybrid_cos_sim_frozen_tune.yml'

method: 'grid'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  use_wandb:
    values:
      - true
  sweep_top_k_split_by:
    values:
      - "n_stores"
  trainer_epochs:
    values:
      - 100
  degradation_scale:
    values:
      - 0.4
      - 0.6
      - 0.8
      - 1.0
      - 1.2
      - 1.4
      - 1.6
      - 1.8
      - 2.0
