# Hybrid Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/hybrid.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  add_gumbel_noise:
    values:
      - false
  anneal_lr:
    values:
      - true
      - false
  buffer_periods:
    values:
      - 50
  clip_by_component:
    values:
      - true
  clip_coef:
    distribution: uniform
    max: 0.2
    min: 0.1
  fixed_cost:
    distribution: categorical
    values:
      - 64
  gae_lambda:
    distribution: uniform
    max: 0.97
    min: 0.95
  gamma:
    distribution: uniform
    max: 0.95
    min: 0.92
  initial_temperature:
    distribution: log_uniform_values
    max: 10
    min: 1
  learning_rate:
    distribution: log_uniform_values
    max: 0.005
    min: 0.0001
  max_grad_norm:
    distribution: uniform
    max: 10
    min: 5
  min_temperature:
    distribution: log_uniform_values
    max: 0.2
    min: 0.001
  normalize_advantages:
    values:
      # - false
      - true
  normalize_observations:
    values:
      - false
  num_epochs:
    values:
      - 5
  pathwise_coef:
    distribution: log_uniform_values
    max: 100
    min: 0.1
  policy_activation:
    values:
      - Tanh
      # - ELU
  reward_scaling:
    values:
      - true
  reward_scaling_pathwise:
    values:
      - true
  use_gae:
    values:
      # - false
      - true
  value_activation:
    values: 
      - Tanh
      # - ELU
  value_function_coef:
    distribution: log_uniform_values
    max: 0.2
    min: 0.1
  # entropy_coef:
  #   distribution: log_uniform_values
  #   max: 1.0
  #   min: 0.001
  continuous_scale:
    values:
      - 1.0
  continuous_shift:
    values: 
      - 5.0
  use_wandb:
    values:
      - true 