# Hybrid Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/hybrid.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  anneal_lr:
    values:
      - false  # Fixed: 60% of top performers used false
  buffer_periods:
    values:
      - 20  # Fixed: median of top performers
  clip_coef:
    values:
      - 0.16  # Fixed: median of top performers
  fixed_cost:
    distribution: categorical
    values:
      - 64
  gae_lambda:
    values:
      - 0.96  # Fixed: median of top performers
  gamma:
    values:
      - 0.93  # Fixed: median of top performers
  learning_rate:
    values:
      - 0.003  # Fixed: median of top performers
  max_grad_norm:
    values:
      - 5.0  # Fixed: median of top performers
  normalize_advantages:
    values:
      - true
  normalize_observations:
    values:
      - false
  num_epochs:
    values:
      - 5  # Fixed: median of top performers
  pathwise_coef:
    values:
      - 10.0  # Fixed: median of top performers
  policy_activation:
    values:
      - Tanh  # Fixed: 90% of top performers used Tanh
  reward_scaling:
    values:
      - true
  reward_scaling_pathwise:
    values:
      - true
  use_gae:
    values:
      - true
  value_activation:
    values: 
      - Tanh
  value_function_coef:
    values:
      - 0.13  # Fixed: median of top performers
  continuous_scale:
    values:
      - 1.0
  continuous_shift:
    values: 
      - 5.0  # Fixed: median of top performers (changed from 1.0 to 1)
  use_wandb:
    values:
      - true