# Hybrid Agent Sweep Configuration
config_files:
  hyperparams: 'configs/policies/hybrid.yml'

method: 'random'
metric:
  name: 'dev/loss/best'
  goal: 'minimize'

parameters:
  anneal_lr:
    values:
      - true
  buffer_periods:
    values:
      - 20
      - 10
  clip_coef:
    distribution: uniform
    max: 0.2
    min: 0.1
  gae_lambda:
    distribution: uniform
    max: 0.97
    min: 0.95
  gamma:
    distribution: uniform
    max: 0.95
    min: 0.92
  learning_rate:
    distribution: log_uniform_values
    max: 0.001
    min: 0.00001
  max_grad_norm:
    distribution: uniform
    max: 10
    min: 1
  normalize_advantages:
    values:
      - true
  normalize_observations:
    values:
      - false
  num_epochs:
    values:
      - 3
      - 5
  pathwise_coef:
    distribution: log_uniform_values
    # distribution: uniform
    max: 100
    # max: 10
    # min: 100.0
    min: 1.0
    # min: 8
  policy_activation:
    values:
      # - ELU
      - Tanh
      # - ReLU
  reward_scaling:
    values:
      - true
      - false
  reward_scaling_pathwise:
    values:
      - true
      - false
  use_gae:
    values:
      - true
  value_activation:
    values:
      - ELU
      - Tanh
      - ReLU
  value_function_coef:
    distribution: log_uniform_values
    max: 1.0
    min: 0.1
  continuous_scale:
    distribution: log_uniform_values
    max: 1000.0
    min: 0.1 
  continuous_shift:
    distribution: uniform
    max: 100.0
    min: 1.0 