# Extends base config
nn_params:
  policy_network:
    name: 'hybrid_policy'
    hidden_layers: [64, 64, 64]
    heads:
      discrete:
        enabled: true
      continuous:
        enabled: true
  
  value_network:
    enabled: true    # Hybrid needs value network 