trainer_params:
  # ... (existing trainer params) ...

optimizer_params:
  'learning_rate': 0.001

nn_params:
  'name': 'hybrid_inventory'
  'neurons_per_hidden_layer':
    'master': [32, 32, 32]
  'inner_layer_activations':
    'master': 'elu'
  'output_layer_activation':
    'master': null

problem_params:
  # Base costs (always active)
  'holding_cost': 1.0
  'shortage_cost': 10.0
  
  # Optional features and their parameters
  'fixed_ordering_cost': 100.0  # Set to null to disable
  'bulk_discounts':  # Set to null to disable
    'thresholds': [50, 100, 200]
    'discounts': [0.0, 0.1, 0.2, 0.3]
  'variable_lead_time':  # Set to null to disable
    'base_lead_time': 1
    'quantity_thresholds': [50, 100]
    'additional_delays': [0, 1, 2]
  'capacity_constraints':  # Set to null to disable
    'max_inventory': 500
    'max_order': 200

action_space:
  'type': 'range_selection'  # or 'fixed_cost'
  'ranges': [[1,3], [5,8], [11,15]]  # Example ranges
  # or for fixed cost:
  # 'continuous_bounds': [0, 100] 