trainer_params : 
  'epochs': 100
  'do_dev_every_n_epochs': 1 
  'print_results_every_n_epochs': 1
  'save_model': false
  'load_previous_model': false
  
  'load_model_path': 'models/saved_models/2024_12_17/vanilla_one_store/1734475197.pt'
  'choose_best_model_on': 'dev_loss'
  'epochs_between_save': 1
  'base_dir': 'models/saved_models'
  'save_model_folders': ['vanilla_one_store']
  'save_model_filename': 'model'

optimizer_params:
  'learning_rate': 0.001

nn_params:
  policy_network:
    name: 'hdpo_policy'
    input_size: 2  # Will be set by environment
    hidden_layers: [32, 32, 32]
    activation: 'elu'
    dropout: 0.1
    batch_norm: true
    heads:
      continuous:
        size: 1  # Single store output
        activation: 'linear'  # Raw output, agent will handle transformation

  value_network:
    hidden_layers: [32, 32]
    activation: 'elu'
    dropout: 0.1
    batch_norm: true